apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-pvc
  namespace: open-webui
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: open-webui
  volumeName: open-webui-pv
  resources:
    requests:
      storage: 10Gi
